---
  - name: Start Apache
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: true

  - name: Restart Apache
    service:
      name: "{{ apache_service }}"
      state: restarted